"""M7: setup.sh can add AIDigest to an existing install without touching existing keys."""

import os
import shutil
import stat
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
FAKE_HASH = "$2a$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ01234"

PRE_PR_ENV = """# Generated by setup.sh on 2026-01-01 00:00 UTC
# DO NOT commit this file — it contains secrets.

ANTHROPIC_API_KEY=sk-ant-fixture-key
SECRET_KEY=1111111111111111111111111111111111111111111111111111111111111111
MASTER_SECRET=2222222222222222222222222222222222222222222222222222222222222222
PARENT_PASSWORD=parent pass $with spaces
CHILD_PIN=4321
DATABASE_URL=postgresql+asyncpg://sage:pw@db.example.com/sagedb?ssl=require
CORS_ORIGINS=https://localhost,http://ui:80
DISABLE_API_DOCS=true
PRODUCTION=true
"""


def _run(tmp: Path, args, stdin: str):
    env = {"PATH": os.environ["PATH"], "HOME": str(tmp),
           "AIDIGEST_HASH_CMD": f"cat >/dev/null; printf '%s\\n' '{FAKE_HASH}'"}
    return subprocess.run(["bash", str(tmp / "setup.sh"), *args], cwd=tmp, input=stdin, capture_output=True,
                          text=True, env=env, timeout=60)


def _prepare(tmp: Path, content: str = PRE_PR_ENV) -> Path:
    shutil.copy(REPO / "setup.sh", tmp / "setup.sh")
    env_file = tmp / ".env"
    env_file.write_bytes(content.encode())
    env_file.chmod(0o600)
    return env_file


ANSWERS = "opsuser\nlong-enough-password-123\npostgresql+asyncpg://aidigest_app:pw@db.example.com/sagedb?ssl=require\n"


def test_aidigest_only_path_appends_and_never_touches_existing_keys(tmp_path):
    env_file = _prepare(tmp_path)
    before = env_file.read_bytes()
    proc = _run(tmp_path, ["--aidigest"], ANSWERS)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    after = env_file.read_bytes()
    assert after.startswith(before), "existing content must be byte-identical (append only)"
    lines = after.decode().splitlines()
    for key in ("SECRET_KEY", "MASTER_SECRET", "DATABASE_URL", "PARENT_PASSWORD"):
        assert [ln for ln in lines if ln.startswith(key + "=")] == \
            [ln for ln in before.decode().splitlines() if ln.startswith(key + "=")]
    added = after[len(before):].decode()
    assert "AIDIGEST_BASIC_AUTH_USER=opsuser\n" in added
    assert f"AIDIGEST_BASIC_AUTH_HASH='{FAKE_HASH}'\n" in added
    assert "AIDIGEST_DATABASE_URL=postgresql+asyncpg://aidigest_app:pw@" in added
    assert "COMPOSE_PROFILES=aidigest\n" in added
    secret = [ln for ln in added.splitlines() if ln.startswith("AIDIGEST_PROXY_SECRET=")][0].split("=", 1)[1]
    assert len(secret) == 64 and int(secret, 16) >= 0
    assert "long-enough-password-123" not in after.decode()
    assert stat.S_IMODE(env_file.stat().st_mode) == 0o600

    proc2 = _run(tmp_path, ["--aidigest"], ANSWERS)   # idempotent
    assert proc2.returncode == 0, proc2.stdout + proc2.stderr
    assert env_file.read_bytes() == after


def test_existing_aidigest_keys_are_kept(tmp_path):
    env_file = _prepare(tmp_path, PRE_PR_ENV + "AIDIGEST_PROXY_SECRET=keepme\nCOMPOSE_PROFILES=other\n")
    before = env_file.read_bytes()
    proc = _run(tmp_path, ["--aidigest"], ANSWERS)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    after = env_file.read_bytes().decode()
    assert after.startswith(before.decode())
    assert after.count("AIDIGEST_PROXY_SECRET=") == 1 and "AIDIGEST_PROXY_SECRET=keepme" in after
    assert after.count("COMPOSE_PROFILES=") == 1
    assert "COMPOSE_PROFILES" in proc.stdout + proc.stderr  # operator told to add the profile by hand


def test_full_setup_on_existing_env_defaults_to_no_change(tmp_path):
    env_file = _prepare(tmp_path)
    before = env_file.read_bytes()
    proc = _run(tmp_path, [], "\n")
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert env_file.read_bytes() == before


def test_full_setup_add_aidigest_choice_is_append_only(tmp_path):
    env_file = _prepare(tmp_path)
    before = env_file.read_bytes()
    proc = _run(tmp_path, [], "a\n" + ANSWERS)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert env_file.read_bytes().startswith(before)
    assert b"AIDIGEST_PROXY_SECRET=" in env_file.read_bytes()


def test_overwrite_requires_typed_confirmation(tmp_path):
    env_file = _prepare(tmp_path)
    before = env_file.read_bytes()
    proc = _run(tmp_path, [], "o\nyes\n")
    assert proc.returncode != 0
    assert env_file.read_bytes() == before
    assert not (tmp_path / ".env.backup").exists(), "nothing may happen without the typed confirmation"
    assert "MASTER_SECRET" in proc.stdout + proc.stderr


def test_aidigest_path_requires_existing_env(tmp_path):
    shutil.copy(REPO / "setup.sh", tmp_path / "setup.sh")
    proc = _run(tmp_path, ["--aidigest"], ANSWERS)
    assert proc.returncode != 0
    assert not (tmp_path / ".env").exists()


def test_empty_aidigest_keys_from_env_example_are_filled_in_place(tmp_path):
    """Round 2 L3: a .env copied from .env.example has empty AIDIGEST_* keys. They are filled in
    place; every non-AIDigest line stays byte-identical and nothing is duplicated."""
    example = (REPO / ".env.example").read_text()
    env_file = _prepare(tmp_path, example)
    proc = _run(tmp_path, ["--aidigest"], ANSWERS)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    after = env_file.read_text()
    before_lines, after_lines = example.splitlines(), after.splitlines()
    aidigest_keys = ("AIDIGEST_PROXY_SECRET=", "AIDIGEST_BASIC_AUTH_USER=", "AIDIGEST_BASIC_AUTH_HASH=",
                     "AIDIGEST_DATABASE_URL=")
    for i, line in enumerate(before_lines):
        if line.startswith(aidigest_keys):
            continue
        assert after_lines[i] == line, f"line {i + 1} changed: {line!r} -> {after_lines[i]!r}"
    for key in aidigest_keys:
        values = [ln for ln in after_lines if ln.startswith(key)]
        assert len(values) == 1, (key, values)
        assert values[0] not in (key, key + "''", key + '""'), values[0]
    assert "AIDIGEST_BASIC_AUTH_USER=opsuser" in after_lines
    assert f"AIDIGEST_BASIC_AUTH_HASH='{FAKE_HASH}'" in after_lines
    assert "COMPOSE_PROFILES=aidigest" in after_lines
    assert stat.S_IMODE(env_file.stat().st_mode) == 0o600
    proc2 = _run(tmp_path, ["--aidigest"], ANSWERS)
    assert proc2.returncode == 0 and env_file.read_text() == after



# ── Round 3 M1: setup.sh refuses user names Caddy/Settings would reject ───────
@pytest.mark.parametrize("user", ["ops admin", " ", 'o"ps', "{ops}", "ops'", "a" * 65, "aidigest-disabled",
                                  # round 4 L1: the Caddyfile heredoc marker, exact or as a substring
                                  "AIDIGEST_VALUE_END", "xAIDIGEST_VALUE_END", "ops-AIDIGEST_VALUE_END",
                                  "AIDIGEST_VALUE_END-ops"])
def test_setup_rejects_unsafe_basic_auth_user(tmp_path, user):
    env_file = _prepare(tmp_path)
    before = env_file.read_bytes()
    proc = _run(tmp_path, ["--aidigest"], user + "\n" + ANSWERS.split("\n", 1)[1])
    assert proc.returncode != 0, proc.stdout + proc.stderr
    assert env_file.read_bytes() == before
    assert not list(tmp_path.glob(".env.aidigest.*")), "no temp file may be left behind"


# ── Rounds 4-5: no signal or I/O failure leaves the temp copy behind or .env truncated ──
# Deterministic: the signal is sent by a hook at a defined point inside the real aidigest_fill_empty
# (no polling, no sleeps), so the result does not depend on scheduling. The hooks shadow the commands
# the function runs (mktemp, printf, mv, cat) with shell functions that call the real command and
# send the signal either to the shell running the function ($$, also correct inside a command
# substitution) or to its whole process group (0: a terminal Ctrl-C, or SIGHUP on an SSH disconnect).
_RECORD = 'builtin printf "%s\\n" "$t" >> "$CREATED"; '
_MKTEMP_RECORD = 'mktemp() { local t; t=$(command mktemp "$@") || return; ' + _RECORD + 'builtin printf "%s\\n" "$t"; }\n'
_SIGNAL_POINTS = {
    # the round-4 race: the signal lands before the file exists (no trap yet in 9dbdc70)
    "before-mktemp": 'mktemp() { _signal; local t; t=$(command mktemp "$@") || return; '
                     + _RECORD + 'builtin printf "%s\\n" "$t"; }\n',
    # the file exists but its name has not reached the shell yet
    "after-mktemp": 'mktemp() { local t; t=$(command mktemp "$@") || return; ' + _RECORD
                    + '_signal; builtin printf "%s\\n" "$t"; }\n',
    "during-copy": _MKTEMP_RECORD
                   + 'printf() { builtin printf "$@"; [[ "${2:-}" != FILLER_2=* ]] || _signal; }\n',
    # the new content is complete and .env is about to be replaced (cat: an in-place rewrite)
    "at-replace": _MKTEMP_RECORD + 'mv() { _signal; command mv "$@"; }\ncat() { _signal; command cat "$@"; }\n',
    # .env has been replaced
    "after-replace": _MKTEMP_RECORD + 'mv() { command mv "$@" || return; _signal; }\n',
}
_SIGNAL_HELPER = 'if [[ "${TARGET:-}" == group ]]; then _signal() { kill -s "$SIG" 0; }; else _signal() { kill -s "$SIG" $$; }; fi\n'
_SIGNUM = {"HUP": 1, "INT": 2, "QUIT": 3, "TERM": 15}
_FILLER = "".join(f"FILLER_{i}=value-{i}\n" for i in range(5))
_ORIGINAL = _FILLER + "AIDIGEST_PROXY_SECRET=\n"
_FILLED = _FILLER + "AIDIGEST_PROXY_SECRET=new\n"


def _fill_empty_script(hook: str) -> str:
    """The real error() helper and the real aidigest_fill_empty block (from its AIDIGEST_TMP global, when
    there is one, to the end of the function), the hook first, then one call."""
    text_ = (REPO / "setup.sh").read_text()
    error_line = next(ln for ln in text_.splitlines() if ln.startswith("error()"))
    func = text_.index("aidigest_fill_empty() {")
    start = text_.find('AIDIGEST_TMP=""')
    start = start if 0 <= start < func else func
    block = text_[start:text_.index("\n}\n", func) + 3]
    return ("set -euo pipefail\nRED=; RESET=\n" + error_line + "\n" + _SIGNAL_HELPER + hook + block
            + 'aidigest_fill_empty "$1" AIDIGEST_PROXY_SECRET "AIDIGEST_PROXY_SECRET=new"\n')


def _run_fill(tmp_path: Path, hook: str, content: str = _ORIGINAL, **env) -> subprocess.CompletedProcess:
    (tmp_path / ".env").write_text(content)
    # start_new_session: the script gets its own process group, so "kill 0" cannot reach pytest
    return subprocess.run(["bash", "-c", _fill_empty_script(hook), "fill", str(tmp_path / ".env")],
                          cwd=tmp_path, env={"PATH": os.environ["PATH"], "CREATED": str(tmp_path / "created.log"),
                                             **env},
                          capture_output=True, text=True, timeout=60, start_new_session=True)


def _created(tmp_path: Path) -> list[str]:
    created = tmp_path / "created.log"
    return created.read_text().split() if created.exists() else []


@pytest.mark.parametrize("target", ["shell", "group"])
@pytest.mark.parametrize("sig", sorted(_SIGNUM))
@pytest.mark.parametrize("point", sorted(_SIGNAL_POINTS))
def test_setup_temp_file_removed_on_interrupt(tmp_path, point, sig, target):
    """HUP/INT/QUIT/TERM at any point: exit 128+signal, the 600-mode temp copy is gone, and .env is
    either untouched (signal before the replace) or completely replaced: never truncated or partial."""
    proc = _run_fill(tmp_path, _SIGNAL_POINTS[point], SIG=sig, TARGET=target)
    names = _created(tmp_path)
    assert len(names) == 1 and names[0].startswith(str(tmp_path / ".env.aidigest.")), names
    assert proc.returncode == 128 + _SIGNUM[sig], (proc.returncode, proc.stdout, proc.stderr)
    assert not Path(names[0]).exists(), "temp file with secrets left behind"
    assert not list(tmp_path.glob(".env.aidigest.*"))
    assert (tmp_path / ".env").read_text() == (_FILLED if point == "after-replace" else _ORIGINAL)


@pytest.mark.parametrize("target", ["shell", "group"])
@pytest.mark.parametrize("point", ["during-copy", "at-replace"])
def test_setup_sigkill_never_truncates_env(tmp_path, point, target):
    """SIGKILL cannot be trapped: the temp file may remain (it is git-ignored), but .env is the old
    file or the complete new one, never partial or empty (in particular not an in-place rewrite)."""
    proc = _run_fill(tmp_path, _SIGNAL_POINTS[point], SIG="KILL", TARGET=target)
    assert proc.returncode == -9, (proc.returncode, proc.stderr)
    assert (tmp_path / ".env").read_text() == _ORIGINAL


_FAILURES = {  # hook, the message that must explain it
    # a real ENOSPC from the kernel for one line of the copy (what a full disk does)
    "disk-full": (_MKTEMP_RECORD + 'printf() { if [[ "${2:-}" == FILLER_2=* ]]; then builtin printf "$@" > /dev/full; '
                  'else builtin printf "$@"; fi; }\n', "Could not write"),
    # cp -p hitting a full disk: a real ENOSPC, the temp copy keeps mktemp's mode 600 (= .env's)
    "copy-fails": (_MKTEMP_RECORD + 'cp() { command cp "$1" /dev/full; }\n', "Could not copy"),
    "mode-not-kept": (_MKTEMP_RECORD + 'cp() { command cp "$@" && chmod 0666 "${@: -1}"; }\n', "mode and owner"),
    "rename-fails": (_MKTEMP_RECORD + "mv() { return 1; }\n", "Could not replace"),
}


@pytest.mark.parametrize("failure", sorted(_FAILURES))
def test_setup_failure_before_rename_leaves_env_untouched(tmp_path, failure):
    """Any failure before the rename: exit 1 with a clear message, .env byte-identical, and the temp
    copy removed by the EXIT cleanup."""
    env_file = tmp_path / ".env"
    hook, message = _FAILURES[failure]
    env_file.write_text(_ORIGINAL)
    env_file.chmod(0o600)   # as setup.sh writes it, so only the step under test can stop the replace
    proc = subprocess.run(["bash", "-c", _fill_empty_script(hook), "fill", str(env_file)],
                          cwd=tmp_path, env={"PATH": os.environ["PATH"], "CREATED": str(tmp_path / "created.log")},
                          capture_output=True, text=True, timeout=60)
    names = _created(tmp_path)
    assert len(names) == 1, names
    assert proc.returncode == 1, (proc.returncode, proc.stdout, proc.stderr)
    assert message in proc.stdout + proc.stderr and ".env was not changed" in proc.stdout + proc.stderr
    assert env_file.read_text() == _ORIGINAL
    assert not Path(names[0]).exists() and not list(tmp_path.glob(".env.aidigest.*"))


def test_setup_fill_keeps_mode_and_owner(tmp_path):
    """.env is replaced by a rename, so the new file must get the old one's mode and owner."""
    env_file = tmp_path / ".env"
    env_file.write_text(_ORIGINAL)
    env_file.chmod(0o640)
    owner = (12345, 23456) if os.geteuid() == 0 else (os.getuid(), os.getgid())
    if os.geteuid() == 0:
        os.chown(env_file, *owner)
    proc = subprocess.run(["bash", "-c", _fill_empty_script(_MKTEMP_RECORD), "fill", str(env_file)],
                          cwd=tmp_path, env={"PATH": os.environ["PATH"], "CREATED": str(tmp_path / "created.log")},
                          capture_output=True, text=True, timeout=60)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    st = env_file.stat()
    assert env_file.read_text() == _FILLED
    assert stat.S_IMODE(st.st_mode) == 0o640
    assert (st.st_uid, st.st_gid) == owner
    assert not list(tmp_path.glob(".env.aidigest.*"))


def test_setup_fill_empty_without_signal_still_fills(tmp_path):
    """Control for the hooks above: with the recording hook and no signal the function completes."""
    proc = _run_fill(tmp_path, _MKTEMP_RECORD, content="A=1\nAIDIGEST_PROXY_SECRET=\nB=2\n")
    assert proc.returncode == 0, proc.stderr
    assert (tmp_path / ".env").read_text() == "A=1\nAIDIGEST_PROXY_SECRET=new\nB=2\n"
    assert len(_created(tmp_path)) == 1
    assert not list(tmp_path.glob(".env.aidigest.*"))


def test_gitignore_covers_leftover_temp_copies(tmp_path):
    """A temp copy left by SIGKILL (mode 600, full of secrets) must not be committable by
    `git add -A`; .env.example files stay tracked."""
    shutil.copy(REPO / ".gitignore", tmp_path / ".gitignore")
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)

    def ignored(path: str) -> bool:
        return subprocess.run(["git", "check-ignore", "-q", "--no-index", path], cwd=tmp_path).returncode == 0

    for path in (".env", ".env.aidigest.Ab3xYz", ".env.backup", "sub/.env.aidigest.Q1w2E3"):
        assert ignored(path), path
    for path in (".env.example", "homeschool-api/.env.example", "setup.sh"):
        assert not ignored(path), path


def test_setup_accepts_a_near_miss_of_the_heredoc_marker(tmp_path):
    env_file = _prepare(tmp_path)
    proc = _run(tmp_path, ["--aidigest"], "aidigest_value_end\n" + ANSWERS.split("\n", 1)[1])
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert "AIDIGEST_BASIC_AUTH_USER=aidigest_value_end\n" in env_file.read_text()


# ── Round 4 L1: caddy-entrypoint.sh replaces a user containing the heredoc marker ──
# The real entrypoint with a stub `caddy` that prints the environment it is started with (the Caddy
# matrix shows the same end to end with the real Caddy image).
SENTINEL_USER = "aidigest-disabled"


def _entrypoint_env(tmp_path: Path, user: str, hash_: str = FAKE_HASH) -> dict:
    stub = tmp_path / "bin"
    stub.mkdir(exist_ok=True)
    (stub / "caddy").write_text("#!/bin/sh\nenv\n")
    (stub / "caddy").chmod(0o755)
    proc = subprocess.run(["sh", str(REPO / "caddy-entrypoint.sh"), "adapt"], capture_output=True, text=True,
                          timeout=30, env={"PATH": f"{stub}:{os.environ['PATH']}", "AIDIGEST_BASIC_AUTH_USER": user,
                                           "AIDIGEST_BASIC_AUTH_HASH": hash_})
    assert proc.returncode == 0, proc.stderr
    return dict(line.split("=", 1) for line in proc.stdout.splitlines() if "=" in line)


@pytest.mark.parametrize("user", ["AIDIGEST_VALUE_END", "xAIDIGEST_VALUE_END", "ops-AIDIGEST_VALUE_END",
                                  "AIDIGEST_VALUE_END-ops", "opsAIDIGEST_VALUE_ENDops"])
def test_entrypoint_replaces_user_containing_the_heredoc_marker(tmp_path, user):
    env = _entrypoint_env(tmp_path, user)
    assert env["AIDIGEST_BASIC_AUTH_USER"] == SENTINEL_USER
    assert env["AIDIGEST_BASIC_AUTH_HASH"] == FAKE_HASH


@pytest.mark.parametrize("user", ["ops", "aidigest_value_end", "AIDIGEST_VALUE_EN"])
def test_entrypoint_keeps_a_valid_user(tmp_path, user):
    assert _entrypoint_env(tmp_path, user)["AIDIGEST_BASIC_AUTH_USER"] == user
