"""M7: setup.sh can add AIDigest to an existing install without touching existing keys."""

import os
import shutil
import stat
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
FAKE_HASH = "$2a$10$abcdefghijklmnopqrstuuABCDEFGHIJKLMNOPQRSTUVWXYZ01234"

PRE_PR_ENV = """# Generated by setup.sh on 2026-01-01 00:00 UTC
# DO NOT commit this file — it contains secrets.

ANTHROPIC_API_KEY=sk-ant-fixture-key
SECRET_KEY=1111111111111111111111111111111111111111111111111111111111111111
MASTER_SECRET=2222222222222222222222222222222222222222222222222222222222222222
PARENT_PASSWORD=parent pass $with spaces
CHILD_PIN=4321
DATABASE_URL=postgresql+asyncpg://sage:pw@db.example.com/sagedb?ssl=require
CORS_ORIGINS=https://localhost,http://ui:80
DISABLE_API_DOCS=true
PRODUCTION=true
"""


def _run(tmp: Path, args, stdin: str):
    env = {"PATH": os.environ["PATH"], "HOME": str(tmp),
           "AIDIGEST_HASH_CMD": f"cat >/dev/null; printf '%s\\n' '{FAKE_HASH}'"}
    return subprocess.run(["bash", str(tmp / "setup.sh"), *args], cwd=tmp, input=stdin, capture_output=True,
                          text=True, env=env, timeout=60)


def _prepare(tmp: Path, content: str = PRE_PR_ENV) -> Path:
    shutil.copy(REPO / "setup.sh", tmp / "setup.sh")
    env_file = tmp / ".env"
    env_file.write_bytes(content.encode())
    env_file.chmod(0o600)
    return env_file


ANSWERS = "opsuser\nlong-enough-password-123\npostgresql+asyncpg://aidigest_app:pw@db.example.com/sagedb?ssl=require\n"


def test_aidigest_only_path_appends_and_never_touches_existing_keys(tmp_path):
    env_file = _prepare(tmp_path)
    before = env_file.read_bytes()
    proc = _run(tmp_path, ["--aidigest"], ANSWERS)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    after = env_file.read_bytes()
    assert after.startswith(before), "existing content must be byte-identical (append only)"
    lines = after.decode().splitlines()
    for key in ("SECRET_KEY", "MASTER_SECRET", "DATABASE_URL", "PARENT_PASSWORD"):
        assert [ln for ln in lines if ln.startswith(key + "=")] == \
            [ln for ln in before.decode().splitlines() if ln.startswith(key + "=")]
    added = after[len(before):].decode()
    assert "AIDIGEST_BASIC_AUTH_USER=opsuser\n" in added
    assert f"AIDIGEST_BASIC_AUTH_HASH='{FAKE_HASH}'\n" in added
    assert "AIDIGEST_DATABASE_URL=postgresql+asyncpg://aidigest_app:pw@" in added
    assert "COMPOSE_PROFILES=aidigest\n" in added
    secret = [ln for ln in added.splitlines() if ln.startswith("AIDIGEST_PROXY_SECRET=")][0].split("=", 1)[1]
    assert len(secret) == 64 and int(secret, 16) >= 0
    assert "long-enough-password-123" not in after.decode()
    assert stat.S_IMODE(env_file.stat().st_mode) == 0o600

    proc2 = _run(tmp_path, ["--aidigest"], ANSWERS)   # idempotent
    assert proc2.returncode == 0, proc2.stdout + proc2.stderr
    assert env_file.read_bytes() == after


def test_existing_aidigest_keys_are_kept(tmp_path):
    env_file = _prepare(tmp_path, PRE_PR_ENV + "AIDIGEST_PROXY_SECRET=keepme\nCOMPOSE_PROFILES=other\n")
    before = env_file.read_bytes()
    proc = _run(tmp_path, ["--aidigest"], ANSWERS)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    after = env_file.read_bytes().decode()
    assert after.startswith(before.decode())
    assert after.count("AIDIGEST_PROXY_SECRET=") == 1 and "AIDIGEST_PROXY_SECRET=keepme" in after
    assert after.count("COMPOSE_PROFILES=") == 1
    assert "COMPOSE_PROFILES" in proc.stdout + proc.stderr  # operator told to add the profile by hand


def test_full_setup_on_existing_env_defaults_to_no_change(tmp_path):
    env_file = _prepare(tmp_path)
    before = env_file.read_bytes()
    proc = _run(tmp_path, [], "\n")
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert env_file.read_bytes() == before


def test_full_setup_add_aidigest_choice_is_append_only(tmp_path):
    env_file = _prepare(tmp_path)
    before = env_file.read_bytes()
    proc = _run(tmp_path, [], "a\n" + ANSWERS)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert env_file.read_bytes().startswith(before)
    assert b"AIDIGEST_PROXY_SECRET=" in env_file.read_bytes()


def test_overwrite_requires_typed_confirmation(tmp_path):
    env_file = _prepare(tmp_path)
    before = env_file.read_bytes()
    proc = _run(tmp_path, [], "o\nyes\n")
    assert proc.returncode != 0
    assert env_file.read_bytes() == before
    assert not (tmp_path / ".env.backup").exists(), "nothing may happen without the typed confirmation"
    assert "MASTER_SECRET" in proc.stdout + proc.stderr


def test_aidigest_path_requires_existing_env(tmp_path):
    shutil.copy(REPO / "setup.sh", tmp_path / "setup.sh")
    proc = _run(tmp_path, ["--aidigest"], ANSWERS)
    assert proc.returncode != 0
    assert not (tmp_path / ".env").exists()


def test_empty_aidigest_keys_from_env_example_are_filled_in_place(tmp_path):
    """Round 2 L3: a .env copied from .env.example has empty AIDIGEST_* keys. They are filled in
    place; every non-AIDigest line stays byte-identical and nothing is duplicated."""
    example = (REPO / ".env.example").read_text()
    env_file = _prepare(tmp_path, example)
    proc = _run(tmp_path, ["--aidigest"], ANSWERS)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    after = env_file.read_text()
    before_lines, after_lines = example.splitlines(), after.splitlines()
    aidigest_keys = ("AIDIGEST_PROXY_SECRET=", "AIDIGEST_BASIC_AUTH_USER=", "AIDIGEST_BASIC_AUTH_HASH=",
                     "AIDIGEST_DATABASE_URL=")
    for i, line in enumerate(before_lines):
        if line.startswith(aidigest_keys):
            continue
        assert after_lines[i] == line, f"line {i + 1} changed: {line!r} -> {after_lines[i]!r}"
    for key in aidigest_keys:
        values = [ln for ln in after_lines if ln.startswith(key)]
        assert len(values) == 1, (key, values)
        assert values[0] not in (key, key + "''", key + '""'), values[0]
    assert "AIDIGEST_BASIC_AUTH_USER=opsuser" in after_lines
    assert f"AIDIGEST_BASIC_AUTH_HASH='{FAKE_HASH}'" in after_lines
    assert "COMPOSE_PROFILES=aidigest" in after_lines
    assert stat.S_IMODE(env_file.stat().st_mode) == 0o600
    proc2 = _run(tmp_path, ["--aidigest"], ANSWERS)
    assert proc2.returncode == 0 and env_file.read_text() == after



# ── Round 3 M1: setup.sh refuses user names Caddy/Settings would reject ───────
@pytest.mark.parametrize("user", ["ops admin", " ", 'o"ps', "{ops}", "ops'", "a" * 65, "aidigest-disabled",
                                  # round 4 L1: the Caddyfile heredoc marker, exact or as a substring
                                  "AIDIGEST_VALUE_END", "xAIDIGEST_VALUE_END", "ops-AIDIGEST_VALUE_END",
                                  "AIDIGEST_VALUE_END-ops"])
def test_setup_rejects_unsafe_basic_auth_user(tmp_path, user):
    env_file = _prepare(tmp_path)
    before = env_file.read_bytes()
    proc = _run(tmp_path, ["--aidigest"], user + "\n" + ANSWERS.split("\n", 1)[1])
    assert proc.returncode != 0, proc.stdout + proc.stderr
    assert env_file.read_bytes() == before
    assert not list(tmp_path.glob(".env.aidigest.*")), "no temp file may be left behind"


# ── Round 4 M1: INT/TERM at any point never leaves the temp copy behind or .env half-written ──
# Deterministic: the signal is sent by a hook at a defined point inside the real aidigest_fill_empty
# (no polling, no sleeps), so the result does not depend on scheduling. The hooks shadow the commands
# the function runs (mktemp, printf, cat) with shell functions that call the real command and send
# the signal either to the shell running the function ($$, also correct inside a command
# substitution) or to its whole process group (0: what a terminal Ctrl-C does).
_RECORD = 'builtin printf "%s\\n" "$t" >> "$CREATED"; '
_MKTEMP_RECORD = 'mktemp() { local t; t=$(command mktemp "$@") || return; ' + _RECORD + 'builtin printf "%s\\n" "$t"; }\n'
_SIGNAL_POINTS = {
    # the challenger's race: the signal lands before the file exists (old code: no trap yet)
    "before-mktemp": 'mktemp() { _signal; local t; t=$(command mktemp "$@") || return; '
                     + _RECORD + 'builtin printf "%s\\n" "$t"; }\n',
    # the file exists but its name has not reached the shell yet
    "after-mktemp": 'mktemp() { local t; t=$(command mktemp "$@") || return; ' + _RECORD
                    + '_signal; builtin printf "%s\\n" "$t"; }\n',
    "during-copy": _MKTEMP_RECORD
                   + 'printf() { builtin printf "$@"; [[ "${2:-}" != FILLER_2=* ]] || _signal; }\n',
    # .env has been truncated for the in-place rewrite and nothing is written yet
    "during-rewrite": _MKTEMP_RECORD + 'cat() { _signal; command cat "$@"; }\n',
}
_SIGNAL_HELPER = 'if [[ "${TARGET:-}" == group ]]; then _signal() { kill -s "$SIG" 0; }; else _signal() { kill -s "$SIG" $$; }; fi\n'
_FILLER = "".join(f"FILLER_{i}=value-{i}\n" for i in range(5))


def _fill_empty_script(hook: str) -> str:
    text_ = (REPO / "setup.sh").read_text()
    start = text_.index("aidigest_fill_empty() {")
    func = text_[start:text_.index("\n}\n", start) + 3]
    return ("set -euo pipefail\n" + _SIGNAL_HELPER + hook + func
            + 'aidigest_fill_empty "$1" AIDIGEST_PROXY_SECRET "AIDIGEST_PROXY_SECRET=new"\n')


def _run_fill(tmp_path: Path, hook: str, **env) -> subprocess.CompletedProcess:
    # start_new_session: the script gets its own process group, so "kill 0" cannot reach pytest
    return subprocess.run(["bash", "-c", _fill_empty_script(hook), "fill", str(tmp_path / ".env")],
                          cwd=tmp_path, env={"PATH": os.environ["PATH"], "CREATED": str(tmp_path / "created.log"),
                                             **env},
                          capture_output=True, text=True, timeout=60, start_new_session=True)


@pytest.mark.parametrize("target", ["shell", "group"])
@pytest.mark.parametrize("sig", ["TERM", "INT"])
@pytest.mark.parametrize("point", sorted(_SIGNAL_POINTS))
def test_setup_temp_file_removed_on_interrupt(tmp_path, point, sig, target):
    """The 600-mode temp copy made while filling empty keys is removed whenever INT/TERM arrives
    (exit 130). .env is either untouched or (signal during the in-place rewrite) completely rewritten:
    never truncated or partial."""
    env_file = tmp_path / ".env"
    content = _FILLER + "AIDIGEST_PROXY_SECRET=\n"
    env_file.write_text(content)
    proc = _run_fill(tmp_path, _SIGNAL_POINTS[point], SIG=sig, TARGET=target)
    created = tmp_path / "created.log"
    names = created.read_text().split() if created.exists() else []
    assert len(names) == 1 and names[0].startswith(str(tmp_path / ".env.aidigest.")), names
    assert proc.returncode == 130, (proc.returncode, proc.stderr)
    assert not Path(names[0]).exists(), "temp file with secrets left behind"
    assert not list(tmp_path.glob(".env.aidigest.*"))
    expected = _FILLER + "AIDIGEST_PROXY_SECRET=new\n" if point == "during-rewrite" else content
    assert env_file.read_text() == expected


def test_setup_fill_empty_without_signal_still_fills(tmp_path):
    """Control for the hooks above: with the recording hook and no signal the function completes."""
    env_file = tmp_path / ".env"
    env_file.write_text("A=1\nAIDIGEST_PROXY_SECRET=\nB=2\n")
    proc = _run_fill(tmp_path, _MKTEMP_RECORD)
    assert proc.returncode == 0, proc.stderr
    assert env_file.read_text() == "A=1\nAIDIGEST_PROXY_SECRET=new\nB=2\n"
    assert len((tmp_path / "created.log").read_text().split()) == 1
    assert not list(tmp_path.glob(".env.aidigest.*"))


def test_setup_accepts_a_near_miss_of_the_heredoc_marker(tmp_path):
    env_file = _prepare(tmp_path)
    proc = _run(tmp_path, ["--aidigest"], "aidigest_value_end\n" + ANSWERS.split("\n", 1)[1])
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert "AIDIGEST_BASIC_AUTH_USER=aidigest_value_end\n" in env_file.read_text()


# ── Round 4 L1: caddy-entrypoint.sh replaces a user containing the heredoc marker ──
# The real entrypoint with a stub `caddy` that prints the environment it is started with (the Caddy
# matrix shows the same end to end with the real Caddy image).
SENTINEL_USER = "aidigest-disabled"


def _entrypoint_env(tmp_path: Path, user: str, hash_: str = FAKE_HASH) -> dict:
    stub = tmp_path / "bin"
    stub.mkdir(exist_ok=True)
    (stub / "caddy").write_text("#!/bin/sh\nenv\n")
    (stub / "caddy").chmod(0o755)
    proc = subprocess.run(["sh", str(REPO / "caddy-entrypoint.sh"), "adapt"], capture_output=True, text=True,
                          timeout=30, env={"PATH": f"{stub}:{os.environ['PATH']}", "AIDIGEST_BASIC_AUTH_USER": user,
                                           "AIDIGEST_BASIC_AUTH_HASH": hash_})
    assert proc.returncode == 0, proc.stderr
    return dict(line.split("=", 1) for line in proc.stdout.splitlines() if "=" in line)


@pytest.mark.parametrize("user", ["AIDIGEST_VALUE_END", "xAIDIGEST_VALUE_END", "ops-AIDIGEST_VALUE_END",
                                  "AIDIGEST_VALUE_END-ops", "opsAIDIGEST_VALUE_ENDops"])
def test_entrypoint_replaces_user_containing_the_heredoc_marker(tmp_path, user):
    env = _entrypoint_env(tmp_path, user)
    assert env["AIDIGEST_BASIC_AUTH_USER"] == SENTINEL_USER
    assert env["AIDIGEST_BASIC_AUTH_HASH"] == FAKE_HASH


@pytest.mark.parametrize("user", ["ops", "aidigest_value_end", "AIDIGEST_VALUE_EN"])
def test_entrypoint_keeps_a_valid_user(tmp_path, user):
    assert _entrypoint_env(tmp_path, user)["AIDIGEST_BASIC_AUTH_USER"] == user
