(() => {
  const root = window.CLAUDE_CERT_BANK_EXPANSIONS = window.CLAUDE_CERT_BANK_EXPANSIONS || {};
  const cards = [], questions = [];
  const place = (n, correct, wrong) => {
    const answer = n % 4;
    const choices = wrong.slice(0, 3);
    choices.splice(answer, 0, correct);
    return { choices, answer };
  };
  const addDomain = (domain, prefix, count, contexts, concepts) => {
    for (let i = 0; i < count; i++) {
      const c = concepts[Math.floor(i / contexts.length) % concepts.length];
      const ctx = contexts[i % contexts.length];
      const id = `AOX-${domain}-${String(i + 1).padStart(3, "0")}`;
      const p = place(i + domain.charCodeAt(1), c.correct, c.wrong);
      questions.push({ id, domain, q: `${ctx} ${c.ask}`, choices: p.choices, answer: p.answer, why: c.why });
    }
    concepts.slice(0, 4).forEach((c, i) => cards.push({
      id: `AOX-C-${domain}-${String(i + 1).padStart(2, "0")}`,
      domain,
      term: c.term,
      definition: c.definition,
      example: c.example
    }));
  };

  addDomain("A1", "AOA1", 23,
    [
      "A finance analyst is preparing a board summary from spreadsheets and meeting notes.",
      "An HR lead is using Claude to interpret a policy for managers.",
      "A customer-success team is using Claude to summarize account risks from several sources."
    ],
    [
      {term:"What is the safest treatment of important factual claims?",definition:"Verify consequential claims against the authoritative source before acting on them.",example:"Revenue figures in a draft board brief are checked against the approved finance system.",ask:"Claude gives a polished answer containing several important facts. What should happen before the answer drives a decision?",correct:"Verify the important claims against the authoritative source",wrong:["Treat polished wording as proof of accuracy","Regenerate until the answer sounds more confident","Remove the source material after generation"],why:"Fluency is not evidence. Consequential facts should be checked against an authoritative source."},
      {term:"What makes an evaluation rubric useful?",definition:"A useful rubric has observable criteria tied to the real task outcome.",example:"A meeting-summary rubric checks decisions, owners, due dates, and risks against the transcript.",ask:"The team wants a repeatable way to judge output quality. Which approach is strongest?",correct:"Use explicit observable criteria tied to task success",wrong:["Judge whether the answer feels intelligent","Prefer whichever answer is longest","Score only formatting and tone"],why:"Evaluation should measure the behavior that matters, not vague impressions."},
      {term:"How should unsupported inference be handled?",definition:"Separate source-supported statements from inference and verify material inferences before use.",example:"Claude labels a customer as likely to churn; the analyst checks whether the source actually supports that conclusion.",ask:"Claude adds a plausible conclusion that is not directly supported by the source. What is the best response?",correct:"Treat the conclusion as an inference and verify it before relying on it",wrong:["Accept it because it is plausible","Convert it into a stronger claim","Hide the source so readers cannot compare"],why:"Plausibility does not make an unsupported inference factual."},
      {term:"Why is confidence different from correctness?",definition:"A confident tone can accompany a wrong answer, so confidence must not replace evidence.",example:"A confident policy explanation is still checked against the current policy text.",ask:"Claude sounds highly certain about an answer. How should that confidence be treated?",correct:"As presentation style, not as proof that the answer is correct",wrong:["As a substitute for source verification","As evidence that no review is needed","As a reason to ignore conflicting data"],why:"Model confidence in wording is not a reliability guarantee."},
      {term:"What should happen when trusted sources conflict?",definition:"Surface the conflict, identify the authoritative source or owner, and resolve it before action.",example:"Two policy documents disagree, so the team checks the current approved policy owner.",ask:"Two trusted sources disagree on an important point. What is the best next step?",correct:"Surface the conflict and resolve it using the authoritative source or owner",wrong:["Average the two statements","Choose the version Claude quoted first","Use the answer with more detail"],why:"Conflicting evidence needs resolution, not arbitrary selection."},
      {term:"Why use representative evaluation cases?",definition:"Representative cases reveal whether quality holds across the real distribution, including edge cases.",example:"A support-summary eval includes routine tickets, escalations, incomplete notes, and ambiguous cases.",ask:"The team wants confidence that a workflow generalizes. Which evaluation design is best?",correct:"Test a representative set including normal and difficult real-world cases",wrong:["Test only one ideal example","Use only examples written by the prompt author","Judge a live demo without saved cases"],why:"Representative test cases reduce the chance that a workflow is optimized only for easy examples."},
      {term:"When should human review remain mandatory?",definition:"Use accountable human review for high-impact, regulated, sensitive, or irreversible decisions.",example:"A manager approves an employment-policy recommendation before it is communicated.",ask:"The output could materially affect a person, customer, or financial decision. What control is most appropriate?",correct:"Require accountable human review before the consequential action",wrong:["Remove review because the output is concise","Ask Claude to self-approve","Use a more persuasive tone"],why:"High-impact decisions need accountable oversight even when the draft looks strong."},
      {term:"Why does source freshness matter?",definition:"Correct reasoning over stale information can still produce a wrong current answer.",example:"A pricing recommendation uses the current approved rate card rather than last quarter's copy.",ask:"The answer is internally consistent, but the source may be outdated. What should the team check?",correct:"Confirm the source is current enough for the decision",wrong:["Increase the output length","Assume older sources are safer","Ask for more confident wording"],why:"Freshness is part of factual reliability when policies, prices, or facts can change."}
    ]);

  addDomain("A2", "AOA2", 17,
    ["A support organization is redesigning a manual case workflow.","An operations team is automating a recurring monthly process."],
    [
      {term:"Why map a workflow before adding Claude?",definition:"Mapping inputs, decisions, outputs, owners, and failure points reveals where Claude adds value safely.",example:"A refund process is mapped before Claude is added to summarize evidence.",ask:"What should the team do before deciding which step to automate?",correct:"Map the current inputs, decisions, outputs, owners, and failure points",wrong:["Start with the largest possible automation","Remove all human steps immediately","Choose a model before understanding the process"],why:"Process understanding should precede automation design."},
      {term:"What is a good first automation boundary?",definition:"Start with a bounded, reversible step that has clear inputs, outputs, and review.",example:"Claude drafts a case summary while an agent still decides the outcome.",ask:"Which pilot design is most appropriate?",correct:"Automate a bounded assistive step with a clear review point",wrong:["Automate every decision at once","Let the model rewrite policy when confused","Make the first pilot irreversible"],why:"Bounded pilots limit risk and create measurable learning."},
      {term:"Where should a human approval gate be kept?",definition:"Keep approval before high-impact, financial, legal, privileged, or irreversible actions.",example:"Claude drafts a cancellation recommendation, but a manager approves the actual cancellation.",ask:"The workflow can trigger a consequential action. What control should remain?",correct:"A human approval gate before the consequential action",wrong:["A prettier output template","A longer conversation history","A rule that the model approves itself"],why:"Approval gates preserve accountability at high-consequence boundaries."},
      {term:"What should remain the source of truth?",definition:"Authoritative business state belongs in the system of record, not only in generated text or chat history.",example:"The CRM remains authoritative for customer status even when Claude summarizes the account.",ask:"Where should authoritative workflow state live?",correct:"In the designated system of record",wrong:["Only in the Claude conversation","Only in a generated summary","In whichever answer sounds newest"],why:"Generated text should not silently replace authoritative operational records."},
      {term:"Why design explicit exception handling?",definition:"A workflow needs a defined path for low-confidence, missing-data, and policy-edge cases.",example:"Cases with missing approval evidence route to a human queue.",ask:"What should happen when required information is missing or the case is outside the normal pattern?",correct:"Route the case through an explicit exception path",wrong:["Let Claude invent the missing information","Force every case through the happy path","Discard the case without recording it"],why:"Exceptions should be anticipated and handled deliberately."},
      {term:"Why assign an owner to each handoff?",definition:"Clear ownership prevents ambiguous responsibility when generated work moves between people and systems.",example:"The account manager owns approval after Claude drafts a client brief.",ask:"How should handoffs be designed?",correct:"Make the responsible owner and acceptance criteria explicit",wrong:["Leave responsibility shared and undefined","Assume Claude owns the final business decision","Remove escalation paths"],why:"Explicit ownership makes the workflow auditable and accountable."},
      {term:"Why prefer reversible automation early?",definition:"Reversible steps make it easier to learn, correct mistakes, and reduce blast radius during adoption.",example:"Claude proposes CRM field changes before automatic writes are enabled.",ask:"Which property is especially valuable in an early pilot?",correct:"The automated action can be reviewed or reversed easily",wrong:["The action is permanent immediately","There is no audit trail","The pilot skips measurement"],why:"Reversibility lowers adoption risk while the workflow is being validated."},
      {term:"What should a workflow pilot measure?",definition:"Measure outcome quality, time saved, error rates, escalation rates, and user impact relevant to the process.",example:"A triage pilot tracks correct routing, handling time, and human override rate.",ask:"Which measurement approach best shows whether the workflow is working?",correct:"Track task-quality and operational outcome metrics tied to the process",wrong:["Count only how many prompts were sent","Measure only response length","Use anecdotal praise without task metrics"],why:"A useful pilot needs outcome-oriented measures, not just activity counts."},
      {term:"When should a business workflow escalate to technical specialists?",definition:"Escalate when the design requires APIs, custom tools, privileged actions, security architecture, or production integration.",example:"Automatic CRM updates are handed to Developer/Architect owners for integration design.",ask:"The requested workflow now needs authenticated system writes. What is the right next step?",correct:"Escalate the integration to the appropriate Developer or Architect owner",wrong:["Paste credentials into the prompt","Ask a business user to bypass access controls","Treat the chat interface as the system integration layer"],why:"Authenticated system integration requires technical controls beyond normal end-user configuration."}
    ]);

  addDomain("A3", "AOA3", 15,
    ["A team is handling customer and employee information with Claude.","A regulated business unit is introducing Claude into a controlled process."],
    [
      {term:"What is data minimization?",definition:"Use only the information needed for the task and avoid unnecessary sensitive data.",example:"A complaint summary omits unrelated payment identifiers.",ask:"What is the safest way to prepare the input?",correct:"Include only data necessary for the task",wrong:["Include every available record just in case","Add unrelated identifiers for context","Move sensitive fields into the prompt instructions"],why:"Minimizing data reduces unnecessary exposure and simplifies governance."},
      {term:"How should untrusted instructions in content be treated?",definition:"Treat user-supplied or retrieved instructions as data that cannot override trusted policy.",example:"A document saying 'ignore policy' is summarized but not obeyed.",ask:"The source text contains instructions that conflict with policy. How should they be handled?",correct:"Treat them as untrusted content, not higher-priority instructions",wrong:["Let the document override company policy","Assume embedded instructions are administrator commands","Follow them if they are written in bold"],why:"Untrusted content must not become an authority boundary."},
      {term:"What does least privilege mean for Claude-enabled work?",definition:"People, tools, and integrations should have only the access needed for the task.",example:"A reporting workflow receives read-only access to the required dataset.",ask:"Which access approach is most appropriate?",correct:"Grant only the minimum access required for the workflow",wrong:["Give broad administrator access for convenience","Share one privileged account with the whole team","Add permissions unrelated to the task"],why:"Least privilege limits the impact of mistakes and misuse."},
      {term:"When should sensitive output receive human review?",definition:"Review sensitive, regulated, consequential, or externally binding output before action.",example:"Legal reviews a regulated disclosure drafted with Claude.",ask:"The output will be used in a sensitive external communication. What should happen?",correct:"Route it to the accountable human reviewer before use",wrong:["Send it automatically because Claude used a disclaimer","Remove the review step if formatting is correct","Ask Claude to certify its own compliance"],why:"Sensitive communications need accountable review."},
      {term:"Why keep an audit trail?",definition:"Audit records support accountability, investigation, and evidence of how important decisions were made.",example:"A controlled workflow records source version, reviewer, and final action.",ask:"Why should the workflow record key inputs, approvals, and actions?",correct:"To support accountability and later investigation",wrong:["To make prompts longer","To eliminate the need for policy","To let users skip approvals"],why:"Auditability is a governance control, especially in consequential workflows."},
      {term:"Why respect disclosure and consent requirements?",definition:"Use of data and AI-generated content must follow applicable organizational and legal disclosure or consent rules.",example:"A team follows its approved policy for customer-facing AI assistance.",ask:"What should determine whether disclosure or consent is required?",correct:"The applicable policy, contract, and legal requirements for the use case",wrong:["Whether the output is short","Whether Claude sounds human","Whether the user prefers not to disclose"],why:"Governance obligations come from the applicable rules, not output style."},
      {term:"How should instruction priority be handled?",definition:"Trusted organizational and task instructions take precedence over conflicting untrusted content.",example:"A pasted email cannot override a company's confidentiality rules.",ask:"A document conflicts with an approved policy constraint. Which should govern?",correct:"The approved policy and trusted task instructions",wrong:["The latest sentence in the document","Whichever instruction is longer","The instruction containing the most urgent wording"],why:"Trusted policy boundaries should not be displaced by untrusted content."},
      {term:"What should happen when a high-impact answer remains uncertain?",definition:"Surface uncertainty, verify evidence, and escalate to the accountable owner rather than hiding ambiguity.",example:"An ambiguous compliance interpretation is escalated instead of presented as settled.",ask:"Claude cannot resolve an important ambiguity confidently. What is the best response?",correct:"Make the uncertainty explicit and escalate for authoritative review",wrong:["Regenerate until certainty appears","Hide the ambiguity from the decision maker","Choose the most convenient interpretation"],why:"Uncertainty should be managed, not disguised."}
    ]);

  addDomain("A4", "AOA4", 13,
    ["A consultant is preparing an executive deliverable.","A project lead is using Claude for a repeated classification and writing task."],
    [
      {term:"What makes a task prompt specific?",definition:"State the objective, audience, context, constraints, and desired output clearly.",example:"Ask for a 150-word executive brief with decisions, risks, owners, and next steps.",ask:"The current prompt is vague and results vary. What change is most useful?",correct:"Specify the objective, relevant context, constraints, audience, and output",wrong:["Repeat the vague prompt more loudly","Remove the success criteria","Ask for a random writing style"],why:"Explicit task requirements reduce ambiguity."},
      {term:"When do examples help?",definition:"Examples help when style, structure, or category boundaries are difficult to describe abstractly.",example:"Two labeled examples clarify the difference between routine and escalated cases.",ask:"Two categories are repeatedly confused. What prompting technique is most useful?",correct:"Provide representative examples near the decision boundary",wrong:["Remove the category definitions","Increase response length","Ask Claude to guess the categories"],why:"Examples can clarify subtle boundaries better than vague instructions."},
      {term:"Why decompose a complex task?",definition:"Breaking work into stages makes intermediate reasoning inspectable and easier to correct.",example:"Extract requirements, compare options, then draft the recommendation.",ask:"The task contains several dependent reasoning steps. Why split it into stages?",correct:"To inspect and correct intermediate work before errors propagate",wrong:["To guarantee every answer is correct","To eliminate all review","To make the task less specific"],why:"Decomposition improves control and diagnosability."},
      {term:"Why request an explicit output format?",definition:"A defined structure makes results easier to review, compare, and reuse.",example:"Require sections for recommendation, evidence, risks, and next actions.",ask:"The output must be reused consistently by a team. What should the prompt include?",correct:"A clear required output structure",wrong:["No formatting guidance at all","A request to be creative without constraints","Only a maximum word count"],why:"Structured outputs improve consistency and reviewability."},
      {term:"What is iterative prompting for?",definition:"Use feedback from an initial result to clarify requirements, fix gaps, and improve the next attempt.",example:"After a draft misses risks, the user adds explicit risk criteria and reruns the task.",ask:"The first result is close but misses one important requirement. What should the user do?",correct:"Refine the instructions based on the observed gap and try again",wrong:["Keep repeating the identical prompt indefinitely","Assume the requirement is impossible","Remove the missing requirement"],why:"Iteration should be driven by observed failure modes."},
      {term:"How can a prompt encourage evidence-aware output?",definition:"Ask the model to distinguish sourced facts, assumptions, and uncertainty when that matters.",example:"A recommendation labels each major claim as sourced evidence or assumption.",ask:"The decision maker needs to know what is evidence versus assumption. What should the prompt request?",correct:"Explicitly separate supported facts, assumptions, and uncertainty",wrong:["Make every statement sound certain","Remove source references","Use stronger adjectives"],why:"Evidence-aware output makes review more defensible."},
      {term:"Why separate instructions from source content?",definition:"Clear boundaries reduce confusion about what Claude should follow versus analyze.",example:"Policy instructions stay outside a tagged customer document.",ask:"The request contains both directions and a large untrusted document. What is the best structure?",correct:"Clearly delimit instructions from the source content",wrong:["Mix both into one unlabeled block","Let the document redefine the task","Put trusted policy inside the untrusted content"],why:"Separation makes the role of each piece of text clearer."}
    ]);

  addDomain("A5", "AOA5", 11,
    ["A marketing department is standardizing recurring Claude work.","A service organization is choosing how to deliver a new Claude-assisted workflow."],
    [
      {term:"When is a Project a good fit?",definition:"Use a Project for recurring work that benefits from stable instructions and a bounded reusable knowledge set.",example:"A marketing Project contains approved brand rules and product messaging.",ask:"The team repeats similar work using the same guidance and documents. What is the best fit?",correct:"Use a Project with durable instructions and relevant knowledge",wrong:["Start from an unrelated blank chat every time","Upload every company file regardless of relevance","Build a custom API integration before validating the workflow"],why:"Projects support recurring work with stable context and knowledge."},
      {term:"When is a one-off chat sufficient?",definition:"A normal conversation is often enough for an isolated task that does not need durable project context.",example:"A user asks for a one-time rewrite of a short internal note.",ask:"The task is isolated and has no reusable knowledge or workflow requirements. What is sufficient?",correct:"Use a normal Claude conversation",wrong:["Create a large permanent knowledge base first","Build a custom integration immediately","Store unrelated documents in a Project"],why:"The simplest product surface should be used when persistent structure is unnecessary."},
      {term:"How should model selection be made?",definition:"Choose based on measured quality, latency, cost, and task requirements rather than always selecting the largest model.",example:"Routine classification uses a faster model after it meets the quality target.",ask:"Several model options can perform the task. How should the team choose?",correct:"Compare them against the task's quality, latency, and cost requirements",wrong:["Always choose the largest model without testing","Choose based only on model name","Ignore the real workflow target"],why:"Model choice should be evidence-driven and task-specific."},
      {term:"Why consider latency and cost?",definition:"A solution must meet user experience and economic requirements as well as output quality.",example:"A high-volume workflow routes routine cases to a fast model and harder cases to a stronger one.",ask:"Two models meet the quality bar, but one is much slower and more expensive. What should influence the choice?",correct:"Use the workflow's latency and cost constraints along with quality",wrong:["Ignore operating cost entirely","Prefer the slowest model by default","Select randomly to avoid bias"],why:"Production fit includes quality, performance, and economics."},
      {term:"When does a task move beyond end-user configuration?",definition:"Authenticated automation, custom tools, APIs, and production system integration require Developer/Architect involvement.",example:"Writing approved summaries is end-user work; automatically updating ERP records is an integration project.",ask:"The workflow now needs authenticated writes to a business system. What is appropriate?",correct:"Move the integration design to the technical Developer/Architect path",wrong:["Paste system credentials into a chat","Ask users to perform unauthorized writes manually","Assume a Project replaces API integration"],why:"Production integrations require technical controls and engineering ownership."},
      {term:"Can a stronger model fix a poor workflow?",definition:"Model capability cannot compensate for stale data, unclear requirements, missing controls, or bad process design.",example:"A model upgrade does not fix a Project that still contains obsolete policy documents.",ask:"The team upgraded the model but still sees the same stale answers. What should they inspect?",correct:"The workflow inputs, source freshness, and process design",wrong:["Only the writing style","Whether answers use enough headings","Whether the model name appears in the output"],why:"Workflow quality and source quality remain essential regardless of model capability."}
    ]);

  addDomain("A6", "AOA6", 11,
    ["A policy team maintains a long-running Claude Project.","A sales organization maintains shared instructions and reference material for recurring work."],
    [
      {term:"What belongs in durable instructions?",definition:"Stable rules that should apply repeatedly, such as audience, process, definitions, and required conventions.",example:"Every account brief must include risks, decisions, owner, and next step.",ask:"Which type of information belongs in the durable configuration?",correct:"Stable guidance that should apply across repeated tasks",wrong:["A one-time request specific to today's case","Temporary facts that expire after one task","Unrelated historical notes"],why:"Durable instructions should contain durable rules."},
      {term:"What makes a good knowledge source?",definition:"It is relevant, trustworthy, current enough, and scoped to the task.",example:"The approved current policy manual is included; obsolete drafts are removed.",ask:"How should the team choose reference material?",correct:"Prefer trusted, relevant, current sources and remove unrelated material",wrong:["Include every draft ever created","Prefer unapproved documents because there are more of them","Keep obsolete sources without labels"],why:"Knowledge quality directly affects answer quality and ambiguity."},
      {term:"Why track source versions?",definition:"Version awareness helps users know whether Claude is reasoning from the current approved material.",example:"The Project records that the 2026 policy replaces the 2025 policy.",ask:"Two versions of a key document exist. What configuration practice is strongest?",correct:"Clearly identify the current approved version and retire or label superseded copies",wrong:["Leave both versions unlabeled","Let Claude guess which one is current","Merge conflicting text without review"],why:"Version clarity reduces contradictory or stale answers."},
      {term:"Why scope a knowledge set?",definition:"A focused set reduces irrelevant retrieval and makes maintenance easier.",example:"A contract-review Project contains approved legal playbooks, not the entire shared drive.",ask:"The Project contains hundreds of irrelevant files. What should the owner do?",correct:"Remove unrelated sources and keep the knowledge set focused on the task",wrong:["Add more unrelated files","Tell users to ignore all context","Duplicate the largest files"],why:"Focused knowledge improves relevance and maintainability."},
      {term:"Why use clear document naming and metadata?",definition:"Clear names, dates, and status labels help humans maintain the right sources and reduce ambiguity.",example:"Policy-Travel-2026-Approved is easier to govern than final_v7_new.pdf.",ask:"What helps maintain a shared knowledge collection over time?",correct:"Use clear names, dates, ownership, and approval status",wrong:["Use ambiguous filenames for flexibility","Remove all dates from documents","Keep ownership undocumented"],why:"Good information hygiene supports reliable ongoing use."},
      {term:"What should happen to obsolete knowledge?",definition:"Remove, archive, or clearly mark superseded material so it is not treated as current guidance.",example:"An outdated price sheet is removed when the approved replacement is published.",ask:"A source is no longer valid. What is the best action?",correct:"Remove or clearly retire it so it cannot be mistaken for current guidance",wrong:["Keep it active without a warning","Duplicate it into every Project","Ask users to remember not to trust it"],why:"Obsolete knowledge creates avoidable reliability problems."}
    ]);

  addDomain("A7", "AOA7", 9,
    ["A weekly reporting workflow has become inconsistent and slow.","A recurring classification workflow is producing unexpected results for some users."],
    [
      {term:"What should be controlled first when results vary?",definition:"Check whether prompt, source material, settings, and task inputs are actually consistent.",example:"Two teams discover they were using different policy versions.",ask:"What should the team compare before assuming the model is unstable?",correct:"Compare prompts, sources, settings, and inputs across the failing runs",wrong:["Change everything at once","Assume every difference is random","Judge only the writing tone"],why:"Troubleshooting starts by controlling variables."},
      {term:"How should excessive context be optimized?",definition:"Remove stale or irrelevant material while preserving the evidence needed for the task.",example:"A weekly report stops carrying months of emails that never affect the result.",ask:"The workflow includes large amounts of irrelevant history. What is the best optimization?",correct:"Prune context that does not materially contribute to the task",wrong:["Add even more history","Delete the required source evidence","Increase output length instead"],why:"Relevant context improves clarity and can reduce cost and latency."},
      {term:"Why reproduce a failure?",definition:"A reproducible failing case makes it possible to isolate the cause and verify a fix.",example:"The team saves the exact prompt, source, and settings for a misclassified case.",ask:"What is the best first diagnostic artifact for an intermittent problem?",correct:"A saved reproducible example with the exact inputs and settings",wrong:["A description from memory only","A completely different test case","A screenshot without the source inputs"],why:"Reproducibility is essential for disciplined troubleshooting."},
      {term:"Why inspect source quality during troubleshooting?",definition:"Incorrect, stale, contradictory, or missing source material can cause poor outputs even with a strong prompt.",example:"A summary error is traced to an outdated spreadsheet rather than the wording of the prompt.",ask:"The prompt looks sound but the answer is still wrong. What should be checked next?",correct:"Verify the quality, freshness, and completeness of the source material",wrong:["Add decorative formatting","Assume the source cannot be the problem","Remove all validation"],why:"Input quality is a major cause of output quality problems."},
      {term:"When should troubleshooting escalate to technical teams?",definition:"Escalate when the issue involves integrations, APIs, authentication, permissions, platform errors, or production controls.",example:"A Project works manually but an automated CRM connector fails authentication, so the issue moves to engineering.",ask:"The problem is now an authenticated integration failure. What is the appropriate next step?",correct:"Escalate to the Developer or Architect owner with the reproducible evidence",wrong:["Keep changing prose prompts only","Share credentials in the chat","Disable access controls"],why:"Technical integration failures require technical diagnosis and ownership."}
    ]);

  root["ccao-f"] = { cards, questions };
})();
