const PROFILE = window.CERT_PROFILE;
const DOMAINS = PROFILE.domains;
const CARDS = window.CCARF_CARDS || [];
const QUESTIONS = window.CCARF_QUESTIONS || [];
const KEY = PROFILE.progressKey;
const DAY = 86400000;
const defaultState = {cardProgress:{},qProgress:{},domainStats:{},mockHistory:[],deck:[],deckPos:0,flipped:false,activeQuiz:null,lastView:"home"};
function clone(x){return JSON.parse(JSON.stringify(x))}
function initialState(){const s=clone(defaultState);Object.keys(DOMAINS).forEach(d=>s.domainStats[d]={attempts:0,correct:0});return s}
function normalize(s){Object.keys(DOMAINS).forEach(d=>{if(!s.domainStats[d])s.domainStats[d]={attempts:0,correct:0}});s.cardProgress=s.cardProgress||{};s.qProgress=s.qProgress||{};s.mockHistory=s.mockHistory||[]}
function load(){try{const raw=localStorage.getItem(KEY);if(raw){const s=Object.assign(initialState(),JSON.parse(raw));normalize(s);return s}}catch(e){}return initialState()}
let state=load(),timerHandle=null;
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function show(id){["home","flashView","quizView","resultView"].forEach(x=>document.getElementById(x).classList.add("hidden"));document.getElementById(id).classList.remove("hidden");state.lastView=id;save()}
function shuf(a){const b=a.slice();for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function esc(s){return String(s).replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]))}
function cardP(id){if(!state.cardProgress[id])state.cardProgress[id]={status:"new",box:0,due:0,seen:0,correct:0};return state.cardProgress[id]}
function qP(id){if(!state.qProgress[id])state.qProgress[id]={attempts:0,correct:0,lastWrong:0};return state.qProgress[id]}
function cardStatus(c){const p=cardP(c.id);return p.box>=4?"mastered":p.seen?"learning":"new"}
function due(c){const p=cardP(c.id);return !p.seen||!p.due||p.due<=Date.now()}
function accuracy(d){const x=state.domainStats[d];return x.attempts?x.correct/x.attempts:null}
function overall(){let a=0,c=0;Object.values(state.domainStats).forEach(x=>{a+=x.attempts;c+=x.correct});return {a,c,p:a?c/a:null}}
function fullBankReady(){if(PROFILE.bankStatus!=="complete")return false;if(QUESTIONS.length<PROFILE.questionCount)return false;return Object.entries(DOMAINS).every(([d,x])=>QUESTIONS.filter(q=>q.domain===d).length>=x.mock)}
function readiness(){const o=overall(),target=PROFILE.adaptive.targetAccuracy||.9,min=PROFILE.adaptive.minDomainAttempts||10;const domainOk=Object.keys(DOMAINS).every(d=>{const a=accuracy(d);return a!==null&&state.domainStats[d].attempts>=min&&a>=target});if(PROFILE.bankStatus!=="complete")return o.a>=40&&domainOk?"STRONG":"BUILD";const mocks=state.mockHistory.slice(-3),mockOk=mocks.length===3&&mocks.every(m=>m.score>=target);if(mockOk&&domainOk&&o.a>=100&&o.p>=target)return "READY";if(o.a>=50)return "BUILD";return "LEARN"}
function updateTrackChrome(){document.title=`${PROFILE.code} Study Simulator`;const h=document.getElementById("certHeading");if(h)h.textContent=`${PROFILE.code} Study Simulator`;const s=document.getElementById("certSubhead");if(s)s.textContent=`${PROFILE.title} • ${PROFILE.level} • adaptive ${PROFILE.role.toLowerCase()} track`;const c=document.getElementById("coverageText");if(c)c.textContent=`${PROFILE.code} uses an isolated ${PROFILE.role} mastery model. Current bank: ${CARDS.length} flashcards and ${QUESTIONS.length} original scenario questions. ${PROFILE.bankStatus==="complete"?"Full blueprint-weighted mock available.":"Adaptive practice is active; full mock remains disabled until the unique bank satisfies every blueprint allocation."}`}
function renderHome(){updateTrackChrome();cardTotal.textContent=CARDS.length;dueCount.textContent=CARDS.filter(due).length;const mastered=CARDS.filter(c=>cardStatus(c)==="mastered").length;cardMastered.textContent=mastered+"/"+CARDS.length;const o=overall();mcqAccuracy.textContent=o.p===null?"—":Math.round(o.p*100)+"%";mockCount.textContent=state.mockHistory.length;readiness.textContent=readiness();blueprint.innerHTML="";Object.entries(DOMAINS).forEach(([d,x])=>{blueprint.innerHTML+=`<div class="name">${esc(x.name)}</div><div class="score">${x.weight}%</div><div class="small">${PROFILE.bankStatus==="complete"?x.mock+" Q":"adaptive"}</div>`});domainStats.innerHTML="<div class='domainGrid'>"+Object.entries(DOMAINS).map(([d,x])=>{const a=accuracy(d);return `<div class="name">${esc(x.name)}</div><div class="score">${a===null?"—":Math.round(a*100)+"%"}</div><div class="small">${state.domainStats[d].attempts} seen</div>`}).join("")+"</div>";const has=(state.deck.length&&state.deckPos<state.deck.length)||state.activeQuiz;resumeBtn.disabled=!has;fillDomainSelect();const ready=fullBankReady();mockBtn.disabled=!ready;mockBtn.textContent=ready?"Start full mock":"Full mock bank building";mockBtn.title=ready?`${PROFILE.questionCount} questions / ${PROFILE.minutes} minutes`:`Adaptive practice is ready now; the full unique mock bank is still being expanded for ${PROFILE.code}.`;const modeText=document.querySelector("#home .modeCards .mode:nth-child(3) .small");if(modeText)modeText.textContent=`Targets weak ${PROFILE.role.toLowerCase()} domains and previously missed concepts.`}
function fillDomainSelect(){cardDomain.innerHTML="<option value='All'>All domains</option>"+Object.entries(DOMAINS).map(([d,x])=>`<option value="${d}">${esc(x.name)}</option>`).join("")}
function startFlash(dueOnly=false){let pool=CARDS.filter(c=>cardDomain.value==="All"||c.domain===cardDomain.value);if(dueOnly)pool=pool.filter(due);state.deck=shuf(pool.map(c=>c.id));state.deckPos=0;state.flipped=false;show("flashView");renderFlash()}
function currentCard(){return CARDS.find(c=>c.id===state.deck[state.deckPos])}
function renderFlash(){if(!state.deck.length||state.deckPos>=state.deck.length){show("home");renderHome();return}const c=currentCard();frontCat.textContent=DOMAINS[c.domain].name;frontText.textContent=c.term;backText.innerHTML=`<div>${esc(c.definition)}</div><div class="fc-example"><strong>Example:</strong> ${esc(c.example)}</div>`;flashCard.classList.toggle("flipped",state.flipped);flashCounter.textContent=`Card ${state.deckPos+1} of ${state.deck.length} • ${cardStatus(c)}`;flashProgress.style.width=((state.deckPos+1)/state.deck.length*100)+"%";save()}
function flip(){state.flipped=!state.flipped;flashCard.classList.toggle("flipped",state.flipped);save()}
function rate(r){const c=currentCard(),p=cardP(c.id),now=Date.now();p.seen++;if(r==="again"){p.box=0;p.due=now+5*60000}else if(r==="hard"){p.box=Math.max(1,p.box);p.due=now+DAY}else if(r==="good"){p.box=Math.min(4,p.box+1);p.correct++;p.due=now+3*DAY}else{p.box=Math.min(5,p.box+2);p.correct++;p.due=now+7*DAY}state.deckPos++;state.flipped=false;renderFlash()}
function randomPractice(n=20){return shuf(QUESTIONS).slice(0,Math.min(n,QUESTIONS.length)).map(q=>q.id)}
function weakScore(d){const s=state.domainStats[d],prior=DOMAINS[d].weight/100;if(!s.attempts)return -0.25-prior/10;return s.correct/s.attempts+Math.min(s.attempts,20)/1000}
function adaptiveSet(n=25){const chosen=[],used=new Set();for(let i=0;i<Math.min(n,QUESTIONS.length);i++){const domains=Object.keys(DOMAINS).sort((a,b)=>weakScore(a)-weakScore(b));let pick=null;for(const d of domains){const candidates=QUESTIONS.filter(q=>q.domain===d&&!used.has(q.id)).sort((a,b)=>{const A=qP(a.id),B=qP(b.id);const aw=A.attempts?A.correct/A.attempts:0,bw=B.attempts?B.correct/B.attempts:0;if(A.lastWrong!==B.lastWrong)return B.lastWrong-A.lastWrong;if(A.attempts!==B.attempts)return A.attempts-B.attempts;return aw-bw});if(candidates.length){pick=candidates[0];break}}if(!pick)pick=shuf(QUESTIONS.filter(q=>!used.has(q.id)))[0];if(!pick)break;used.add(pick.id);chosen.push(pick.id)}return chosen}
function weightedMock(){if(!fullBankReady())return[];const ids=[];Object.entries(DOMAINS).forEach(([d,x])=>ids.push(...shuf(QUESTIONS.filter(q=>q.domain===d)).slice(0,x.mock).map(q=>q.id)));return shuf(ids)}
function startQuiz(mode){if(mode==="mock"&&!fullBankReady()){alert(`${PROFILE.code} adaptive practice is ready, but the full mock bank is still being expanded to ${PROFILE.questionCount} unique blueprint-weighted questions.`);return}let ids=mode==="adaptive"?adaptiveSet(25):mode==="mock"?weightedMock():randomPractice(20);if(!ids.length){alert("No questions are available for this track yet.");return}state.activeQuiz={mode,ids,pos:0,answers:[],started:Date.now(),deadline:mode==="mock"?Date.now()+PROFILE.minutes*60000:null,answered:false};save();show("quizView");renderQuiz();startTimer()}
function startTimer(){clearInterval(timerHandle);if(!state.activeQuiz||!state.activeQuiz.deadline){timer.textContent="";return}const tick=()=>{const ms=state.activeQuiz.deadline-Date.now();if(ms<=0){clearInterval(timerHandle);finishQuiz(true);return}const m=Math.floor(ms/60000),s=Math.floor((ms%60000)/1000);timer.textContent=`${m}:${String(s).padStart(2,"0")}`};tick();timerHandle=setInterval(tick,1000)}
function currentQ(){const t=state.activeQuiz;return QUESTIONS.find(q=>q.id===t.ids[t.pos])}
function renderQuiz(){const t=state.activeQuiz;if(!t){show("home");renderHome();return}if(t.pos>=t.ids.length){finishQuiz(false);return}const q=currentQ();quizTitle.textContent=t.mode==="mock"?`${PROFILE.code} Full Mock`:t.mode==="adaptive"?`${PROFILE.code} Adaptive Mode`:`${PROFILE.code} Multiple Choice`;quizCounter.textContent=`Question ${t.pos+1} of ${t.ids.length} • ${DOMAINS[q.domain].name}`;quizProgress.style.width=(t.pos/t.ids.length*100)+"%";quizBody.innerHTML=`<div class="qbox"><div class="qtext">${esc(q.q)}</div><div id="choices"></div><div id="feedback" class="hidden"></div></div>`;q.choices.forEach((c,i)=>{const b=document.createElement("button");b.className="choice";b.textContent=String.fromCharCode(65+i)+". "+c;b.onclick=()=>answer(i);choices.appendChild(b)})}
function answer(choice){const t=state.activeQuiz,q=currentQ(),correct=choice===q.answer,p=qP(q.id);p.attempts++;if(correct)p.correct++;else p.lastWrong=Date.now();const ds=state.domainStats[q.domain];ds.attempts++;if(correct)ds.correct++;t.answers.push({id:q.id,choice,correct,domain:q.domain});t.answered=true;save();if(t.mode==="mock"){t.pos++;t.answered=false;renderQuiz();return}[...document.querySelectorAll(".choice")].forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add("correct");if(i===choice&&!correct)b.classList.add("wrong")});feedback.className="notice";feedback.style.marginTop="13px";feedback.innerHTML=`<strong>${correct?"Correct":"Not quite"}</strong><br>${esc(q.why)}<br><button class="btn" id="nextQ" style="margin-top:10px">Next</button>`;nextQ.onclick=()=>{t.pos++;t.answered=false;renderQuiz()}}
function finishQuiz(timedOut){clearInterval(timerHandle);const t=state.activeQuiz;if(!t)return;const total=t.answers.length,correct=t.answers.filter(a=>a.correct).length,score=total?correct/total:0;if(t.mode==="mock")state.mockHistory.push({date:new Date().toISOString(),score,correct,total,timedOut:!!timedOut});const result={mode:t.mode,answers:t.answers,score,correct,total,timedOut:!!timedOut};state.activeQuiz=null;save();showResults(result)}
function showResults(r){show("resultView");resultTitle.textContent=r.mode==="mock"?`${PROFILE.code} Full Mock Results`:r.mode==="adaptive"?`${PROFILE.code} Adaptive Results`:`${PROFILE.code} Practice Results`;resultScore.textContent=Math.round(r.score*100)+"%";resultText.textContent=`${r.correct} of ${r.total} answered correctly${r.timedOut?" before time expired":""}. This is a practice accuracy score, not Anthropic's scaled score.`;const by={};Object.keys(DOMAINS).forEach(d=>by[d]={a:0,c:0});r.answers.forEach(x=>{by[x.domain].a++;if(x.correct)by[x.domain].c++});resultDomains.innerHTML="<div class='domainGrid'>"+Object.entries(DOMAINS).map(([d,x])=>`<div class="name">${esc(x.name)}</div><div class="score">${by[d].a?Math.round(by[d].c/by[d].a*100)+"%":"—"}</div><div class="small">${by[d].a} Q</div>`).join("")+"</div>";resultReview.innerHTML="";r.answers.filter(a=>!a.correct).forEach(a=>{const q=QUESTIONS.find(x=>x.id===a.id),div=document.createElement("div");div.className="item";div.innerHTML=`<strong>${esc(q.q)}</strong><div class="small" style="margin-top:5px">Correct: ${String.fromCharCode(65+q.answer)}. ${esc(q.choices[q.answer])}</div><div class="small">${esc(q.why)}</div>`;resultReview.appendChild(div)});renderHome()}
function resume(){if(state.activeQuiz){show("quizView");renderQuiz();startTimer();return}if(state.deck.length&&state.deckPos<state.deck.length){show("flashView");renderFlash();return}show("home");renderHome()}
function exportState(){const b=new Blob([JSON.stringify({track:PROFILE.code,state},null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`${PROFILE.code.toLowerCase()}-study-progress.json`;a.click();URL.revokeObjectURL(u)}
function importState(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result),incoming=x.state||x;state=Object.assign(initialState(),incoming);normalize(state);save();renderHome();alert("Progress imported.")}catch(e){alert("Invalid progress file.")}};r.readAsText(file)}
function resetAll(){if(confirm(`Reset all ${PROFILE.code} study progress? Export a backup first if needed.`)){state=initialState();save();renderHome()}}
flashBtn.onclick=()=>startFlash(false);dueBtn.onclick=()=>startFlash(true);mcqBtn.onclick=()=>startQuiz("mcq");adaptiveBtn.onclick=()=>startQuiz("adaptive");mockBtn.onclick=()=>startQuiz("mock");resumeBtn.onclick=resume;flashCard.onclick=flip;flipBtn.onclick=flip;document.querySelectorAll("[data-rate]").forEach(b=>b.onclick=()=>rate(b.dataset.rate));stopFlash.onclick=()=>{save();show("home");renderHome()};stopQuiz.onclick=()=>{clearInterval(timerHandle);save();show("home");renderHome()};homeBtn.onclick=()=>{show("home");renderHome()};adaptiveFromResult.onclick=()=>startQuiz("adaptive");exportBtn.onclick=exportState;importFile.onchange=e=>{if(e.target.files[0])importState(e.target.files[0])};resetBtn.onclick=resetAll;window.addEventListener("beforeunload",save);document.addEventListener("keydown",e=>{if(!flashView.classList.contains("hidden")&&e.code==="Space"){e.preventDefault();flip()}});renderHome();
